// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj02laZjA6AcxzwBIxh_qyrpHgh7O5tLc',
    appId: '1:593353731916:web:b1e8eb22e99353fc4aa9e9',
    messagingSenderId: '593353731916',
    projectId: 'agriconnect-8e92f',
    authDomain: 'agriconnect-8e92f.firebaseapp.com',
    storageBucket: 'agriconnect-8e92f.appspot.com',
    measurementId: 'G-WSY5S145FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRoZcZhhIJnu7rvwBCEhXEKdxiqTYPZHs',
    appId: '1:593353731916:android:3c33d6834be2c06b4aa9e9',
    messagingSenderId: '593353731916',
    projectId: 'agriconnect-8e92f',
    storageBucket: 'agriconnect-8e92f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5lQ8hJnem6pKIxW9BpXuA_TuvSigBSY',
    appId: '1:593353731916:ios:c126dffad18c2bcf4aa9e9',
    messagingSenderId: '593353731916',
    projectId: 'agriconnect-8e92f',
    storageBucket: 'agriconnect-8e92f.appspot.com',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP5lQ8hJnem6pKIxW9BpXuA_TuvSigBSY',
    appId: '1:593353731916:ios:ec4c18f8661dc9674aa9e9',
    messagingSenderId: '593353731916',
    projectId: 'agriconnect-8e92f',
    storageBucket: 'agriconnect-8e92f.appspot.com',
    iosBundleId: 'com.example.agriconnect.RunnerTests',
  );
}
